apiVersion: v1
kind: Service
metadata:
  #name: {{ include "django-app.fullname" . }}
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    #app: {{ include "django-app.name" . }}
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
